SELECT Pname, Hours, Ssn, Fname, Lname
FROM EMPLOYEE
LEFT JOIN WORKS_ON ON EMPLOYEE.Ssn = WORKS_ON.Essn
LEFT JOIN PROJECT ON WORKS_ON.Pno = PROJECT.Pnumber
LEFT JOIN DEPARTMENT ON EMPLOYEE.Dno = DEPARTMENT.Dnumber
WHERE DEPARTMENT.Dname = 'Hardware'
ORDER BY Pname ASC, Hours DESC, Lname ASC
